version: '3'
services:
  main:
    build: .
    container_name: abysmal-api
    restart: always
    ports:
      #* change this port depending on where this is deployed
      - "5000:8080"
    environment:
      - CONTACT_WEBHOOK